steps:
  - name: ":shipit:"
    command: ".buildkite/deploy.sh"
    branches: "main"
    agents:
      queue: "oss-deploy"
    plugins:
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: arn:aws:iam::${ROLE_ACCOUNT_ID}:role/pipeline-buildkite-emojis
          session-tags:
            - organization_slug
            - organization_id
            - pipeline_slug
            - build_branch
